/// <reference path="../LootTemplate.ts"/>

module TS.SpaceTac.Equipments {
    export class ForceField extends LootTemplate {
        constructor() {
            super(SlotType.Shield, "Force Field", "A basic force field, generated by radiating waves of compressed energy");

            this.setSkillsRequirements({ "skill_photons": istep(1, irepeat(2)) });
            this.addAttributeEffect("shield_capacity", istep(100, irepeat(40)));
        }
    }
}
