/// <reference path="../LootTemplate.ts"/>

module TS.SpaceTac.Equipments {
    export class ForceField extends LootTemplate {
        constructor() {
            super(SlotType.Shield, "Force Field", "A basic force field, generated by radiating waves of compressed energy", 95);

            this.setSkillsRequirements({ "skill_photons": leveled(1, 2) });
            this.addAttributeEffect("shield_capacity", leveled(80));
        }
    }

    export class GravitShield extends LootTemplate {
        constructor() {
            super(SlotType.Shield, "Gravit Shield", "A shield able to repel damage and enemies using micro-gravity wells", 140);

            this.setSkillsRequirements({ "skill_gravity": leveled(2, 3) });
            this.addAttributeEffect("shield_capacity", leveled(60));
            this.addFireAction(irepeat(2), irepeat(0), leveled(300, 10), [
                new EffectTemplate(new RepelEffect(), { value: leveled(100, 5) })
            ]);
        }
    }

    export class InverterShield extends LootTemplate {
        constructor() {
            super(SlotType.Shield, "Inverter Shield", "An antimatter shield that tries to cancel inbound energy", 258);

            this.setSkillsRequirements({ "skill_antimatter": leveled(2, 1.5), "skill_time": leveled(1, 1) });
            this.addAttributeEffect("shield_capacity", leveled(140));
            this.addAttributeEffect("power_capacity", leveled(-0.2, -0.2));
        }
    }
}
